project:
  type: website

website:
  title: "Amisha Vatsa | ETC5523 Communicating with Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/avat0006-ai

format:
  html:
    theme: cosmo
    css: styles.css



